### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Fasihi-Rad** [darealshinji/embed-ass#2]
Hi, Thank you for making this useful tool.
I get some installation error, and somehow I could solved those.
First one, I get this error : 
`install: cannot stat 'src/embed-ass': No such file or directory`
when I ran `sudo make install`
So, I changed **Makefile** line 3 to `SCRIPT  = embed-ass.in` and it's worked.
second one :
`install: cannot stat 'copyright': No such file or directory`
and the error is gone when I renamed the **COPYING** file to **copyright**.

**Comment by darealshinji** [comment]
Thanks for the fix.
